# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Instagram' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Then', '2.7.0'
  pod 'SnapKit', '5.0.1'

  pod 'SwiftGen', '~> 6.0'

  pod 'RxSwift', '6.2.0'
  pod 'RxCocoa', '6.2.0'
  pod 'RxOptional', '5.0.2'
  pod 'RxGesture', '4.0.2'
  pod 'RxKeyboard', '2.0.0'

  pod 'Moya', '15.0.0'
  pod 'Moya/RxSwift', '15.0.0'

  pod 'ReactorKit', '3.1.0'

  # Pods for Instagram

end
